### ISSUE TITLE
tinkers stone pickaxe head quest

### ISSUE THREAD

**Issue by JackOnRR** [benbenlaw/seaopolis#40]
tinkers stone pick head quest will not complete despite having a stone pick head in your inventory

**Comment by merphle** [comment]
I had the same problem. The stone pickaxe head quest is dependent on the "Cobblestone" quest. Just pick up a piece of cobblestone in order to complete the stone pickaxe head quest.

The stone pickaxe head quest should be dependent on the "Stone" quest instead of "Cobblestone", since a stone pickaxe head can be crafted using vanilla stone, before cobblestone is obtained.
